- name: play level vars
  hosts: local
  connection: local
  vars:               # This will access by task level vars if we specify the same variable name in task level vars
    firstname: MOHAN
    lastname: Reddy
    age: 29
  tasks:
    - name: print firstname
      vars:
        firstname: REDDY
      ansible.builtin.debug:
        msg: "My First Name is {{ firstname }} and my last name is {{ lastname }} and I am {{ age }} years old "